### ISSUE TITLE
Valygar keep telling how to open the sphere 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1292]
#### Bug description
After finishing the planar sphere and exiting Valygar tell me how to open it.
Pressing CTRL+M on him:

```
[Actor/DEBUG]: Debugdump of Actor Valygar (Valygar, Valygar):
Scripts: valygar <none> <none> <none> default <none> <none> dplayer2
Area:       ar0400 ([754.745])
Dialog:     valygarj    TalkCount:  2
Global ID:  10584   PartySlot: 5
Script name:valygar    Current action: -1    Total: 0
Int. Flags: 0x452a04    MC Flags: 0x8000    Allegiance: 2   current allegiance:2
Class:      12   current class:12    Kit: 16392 (base: 16392)
Race:       1   current race:1
Gender:     1   current gender:1
Specifics:  0   current specifics:0
Alignment:  21   current alignment:21
Morale:     10   current morale:10
Moralebreak:5   Morale recovery:60
Visualrange:28 (Explorer: 1)
Fatigue: 0 (current: 0)   Luck: 0
Movement rate: 10 (current: 10)

Levels (average: 9):
RANGER: 9    
current HP:83
Mod[IE_ANIMATION_ID]: 0x6100 ResRef:chmb2 Stance: 1
TURNUNDEADLEVEL: 0 current: 0
Colors:       1616907545   960051513   757935405   1465341783   1600066403   1650614813   0
WaitCounter: 0
LastTarget: 0 <NULL>    LastSpellTarget: 0 <NULL>
LastTalked: 0 <NULL>
INVENTORY:
 1:   npchan - (0 0 0) Fl:0x6c21 Wt: 0 x 9Lb
 5:   brac06 - (0 0 0) Fl:0x6c21 Wt: 0 x 2Lb
10:     FIST - (1 0 0) Fl:0x2029 Wt: 0 x 0Lb
13:   arow08 - (37 0 0) Fl:0x6ce0 Wt: 40 x 0Lb
15:   potn52 - (2 0 0) Fl:0x6ca1 Wt: 5 x 1Lb
18:   dagg01 - (1 0 0) Fl:0x2c21 Wt: 0 x 1Lb
19:   arow09 - (40 0 0) Fl:0x6ca1 Wt: 40 x 0Lb
20:   arow02 - (2 0 0) Fl:0x6ca0 Wt: 40 x 0Lb
21:   arow09 - (40 0 0) Fl:0x6ca1 Wt: 40 x 0Lb
23:   sw1h43 - (1 0 0) Fl:0x2c21 Wt: 0 x 6Lb
26:    bow03 - (1 0 0) Fl:0xae21 Wt: 0 x 3Lb
27:   sper02 - (1 0 0) Fl:0x6e21 Wt: 0 x 5Lb
35:   npsw04 - (1 0 0) Fl:0x6c21 Wt: 0 x 4Lb
36:   sper01 - (1 0 0) Fl:0x2e21 Wt: 0 x 5Lb
37:    bow09 - (1 0 0) Fl:0xee21 Wt: 0 x 8Lb
Equipped: -22       EquippedHeader: 0
Total weight: 45
SPELLBOOK:
 Known spells:
  0:  sppr101 L: 0 T: 0
  1:  sppr103 L: 0 T: 0
  2:  sppr104 L: 0 T: 0
  3:  sppr105 L: 0 T: 0
  4:  sppr110 L: 0 T: 0
  5:  sppr111 L: 0 T: 0
  6:  sppr113 L: 0 T: 0
 Memorized spells:
  0:  sppr103 1
 Known spells:
  0:  spcl311 L: 0 T: 2
  1:  spcl311 L: 0 T: 2
  2:  spcl311 L: 0 T: 2
  3:  spcl311 L: 0 T: 2
  4:  spcl311 L: 0 T: 2
 Memorized spells:
  0:  spcl311 1
  1:  spcl311 1
  2:  spcl311 1
  3:  spcl311 1
  4:  spcl311 1
EFFECT QUEUE:
  0: 0x00: ACVsDamageTypeModifier (2, 16) S:npchan
  1: 0xe9: Proficiency (2, 94) S:
  2: 0xe9: Proficiency (2, 98) S:
  3: 0xe9: Proficiency (2, 104) S:
  4: 0xe9: Proficiency (2, 114) S:
  5: 0xe9: Proficiency (2, 94) S:
  6: 0xe9: Proficiency (2, 98) S:
  7: 0xe9: Proficiency (2, 104) S:
  8: 0xe9: Proficiency (1, 113) S:
  9: 0xe9: Proficiency (2, 114) S:
 10: 0x113: HideInShadowsModifier (20, 0) S:spcl331
 11: 0x3b: StealthModifier (20, 0) S:spcl331
 12: 0x107: BackstabModifier (1, 0) S:spcl332
 13: 0x107: BackstabModifier (1, 0) S:spcl332
 14: 0x91: DisableCasting (0, 0) S:npchan
 15: 0x07: Color:SetPalette (29, 5) S:npchan
 16: 0x07: Color:SetPalette (99, 4) S:npchan
 17: 0x07: Color:SetPalette (25, 0) S:npchan
 18: 0x00: ACVsDamageTypeModifier (2, 8) S:npchan
 19: 0x00: ACVsDamageTypeModifier (-2, 1) S:npchan
 20: 0x1e: FireResistanceModifier (25, 0) S:npchan
 21: 0x8e: Icon:Display (0, 16) S:npchan
 22: 0x8e: Icon:Display (0, 24) S:npchan
 23: 0x8e: Icon:Display (0, 28) S:npchan
 24: 0x1f: MagicDamageResistanceModifier (25, 0) S:npchan
 25: 0x1b: AcidResistanceModifier (25, 0) S:npchan
 26: 0x8e: Icon:Display (0, 52) S:npchan
 27: 0x128: Protection:Animation (0, 5) S:npchan
 28: 0x10b: Protection:String (14780, 5) S:npchan
 29: 0x10b: Protection:String (14672, 5) S:npchan
 30: 0x10b: Protection:String (8364, 5) S:npchan
 31: 0x65: Protection:Opcode (0, 5) S:npchan
 32: 0xa9: Icon:Disable (0, 0) S:npchan
 33: 0xa9: Icon:Disable (0, 1) S:npchan
 34: 0xce: Protection:Spell (0, 0) S:npchan
 35: 0xce: Protection:Spell (0, 0) S:npchan
 36: 0xce: Protection:Spell (0, 0) S:npchan
 37: 0xa9: Icon:Disable (0, 43) S:npchan
 38: 0xce: Protection:Spell (0, 0) S:npchan
 39: 0x2c: StrengthModifier (18, 1) S:brac06
 40: 0x61: StrengthBonusModifier (100, 1) S:brac06
 41: 0x07: Color:SetPalette (19, 20) S:bow09
 42: 0x07: Color:SetPalette (13, 16) S:bow09
 43: 0x01: AttacksPerRoundModifier (2, 1) S:bow09

```

GemRB version: v0.8.8

#### Steps to reproduce
1. Get out of the planar sphere
2. Get down the first stairs
3. Get down the second stairs

#### Expected behavior
The dialog only appear once

#### Screenshots
![image](https://user-images.githubusercontent.com/1820598/122143881-bbd14580-ce28-11eb-847b-e577afc49367.png)

**Comment by lynxlynxlynx** [comment]
It triggers if `Global("ValygarSeesOrb","GLOBAL",1)` then immediately sets it to 2. So unexpected. Do you have a save?

**Comment by rsantellan** [comment]
I have this before leaving the sphere.
[000000041-Master of the sphere.tar.gz](https://github.com/gemrb/gemrb/files/6662924/000000041-Master.of.the.sphere.tar.gz)

**Comment by lynxlynxlynx** [comment]
In this save he never spoke about it before. Are you sure it triggered already on the way in? Eg. you didn't jump over the stairs or something?

These are the conditions:
```
IF
	IsOverMe("Valygar")  // Valygar
	InParty("Valygar")  // Valygar
	IfValidForPartyDialog("Valygar")  // Valygar
	!StateCheck("Valygar",STATE_SLEEPING)  // Valygar
	Global("ValygarSeesOrb","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("ValygarSeesOrb","GLOBAL",1)
		StartCutSceneMode()
		ActionOverride("Valygar",StartDialogNoSet(Player1))
END
```

Do you have a save before entering the vicinity of the sphere in the slums?

**Comment by rsantellan** [comment]
https://user-images.githubusercontent.com/1820598/122266372-1f528600-ceb0-11eb-9030-af550af43826.mp4

[000000043-Before entering the sphere.tar.gz](https://github.com/gemrb/gemrb/files/6664807/000000043-Before.entering.the.sphere.tar.gz)

I didn't jump the stairs any time (Didn't even though about that)

**Comment by lynxlynxlynx** [comment]
Works fine here as well, even after exiting. Maybe it was the same fallout from a dialog bug I fixed earlier.

**Comment by rsantellan** [comment]
@lynxlynxlynx which bug was the one you fixed ? So I can see the changes.

**Comment by lynxlynxlynx** [comment]
it was generic, deep in the core scripting code.

**Comment by rsantellan** [comment]
I try last tag and still happen the same. Is only in the master the change ? Regards

**Comment by lynxlynxlynx** [comment]
The save is bad, no code will fix it.

**Comment by rsantellan** [comment]
> The save is bad, no code will fix it.

Okay! I will try from one before entering first time.
