### ISSUE TITLE
MSVC Debug build: Dialogue displays in reverse order 

### ISSUE THREAD

**Issue by DudeMcDude** [gemrb/gemrb#1655]
#### Bug description
Dialogue option are rendered in the reverse order.
They do go to the correct response node (e.g. clicking the last node in the example below will actually pick "Er ok I'll be back" and end the dialogue)

#### Steps to reproduce
Demo stage, talk to the man

#### Expected behavior
Should display in the right order :)

#### Screenshots

![image](https://user-images.githubusercontent.com/11220053/180867862-be9cfb83-bd64-4e16-8390-2e1f8d73409a.png)

Note that although the order is reversed, the dialog options render nicely, which causes me to think it's a deeper bug (might catch two birds with one stone)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Probably related to the same thing that has been fixed in the last weeks.

**Comment by bradallred** [comment]
I can't see anything recent that should have changed the order. `SpanSelector` is built with a vector, so it should be whatever order the vector is in.

**Comment by lynxlynxlynx** [comment]
The order is fine for me as of my latest push (5f6985b).

**Comment by lynxlynxlynx** [comment]
This got broken today, I can reproduce on master. So it's a side effect of the last view commit.

**Comment by bradallred** [comment]
interesting, I'm still not sure why view order affects the layout tho.

**Comment by bradallred** [comment]
I thought this would fix it, but it seems not...

```diff
diff --git a/gemrb/core/GUI/View.cpp b/gemrb/core/GUI/View.cpp
index f716e4ee5..855afcf5a 100644
--- a/gemrb/core/GUI/View.cpp
+++ b/gemrb/core/GUI/View.cpp
@@ -408,7 +408,6 @@ void View::AddSubviewInFrontOfView(View* front, const View* back)
        if (back != nullptr) {
                it = std::find(subViews.begin(), subViews.end(), back);
                assert(it != subViews.end());
-               ++it;
        }
 
        const View* super = front->superView;
@@ -422,7 +421,11 @@ void View::AddSubviewInFrontOfView(View* front, const View* back)
                        front->superView->RemoveSubview(front);
                }
                // remember, being "in front" means coming after in the list
-               subViews.insert(it, front);
+               if (it != subViews.end()) {
+                       subViews.insert(++it, front);
+               } else {
+                       subViews.insert(it, front);
+               }
        }
 
        front->superView = this;
```
