### ISSUE TITLE
[bug] Invisible Shadows / Shadow Fiends in BG2

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#193]
**Description**
Shadows and Shadow Fiends are not drawn due to the following errors:

`[CharAnimations/ERROR]: Couldn't create animationfactory: mhsdg11 (7703)`
`[ResourceManager/ERROR]: Couldn't find 'mhsdg11.bam'.`
`[CharAnimations/ERROR]: Couldn't create animationfactory: mhsdg12 (7703)`
`[ResourceManager/ERROR]: Couldn't find 'mhsdg12.bam'.`

I remember a problem with shadow animations from when I last played a couple of years ago, could have sworn it was fixed, though. Game is BG2, tested on an unmodded installation.

EDIT: Found it on G3:
https://www.gibberlings3.net/forums/topic/28618-solved-animations-for-shadows-dont-work-fixed/

**GemRB version:** 
0.8.5-git, compiled August 31th

**To Reproduce**
- start / load a BG2 game
- move to an area with shadow creatures: AR1404 Shadow Temple Land shadowed

**Comment by lynxlynxlynx** [comment]
This is typically caused by atypical animations (eg. they're missing these files and should fall back to some other animation stance). You previously just worked around this, which of course shouldn't be necessary.

**Comment by caillean7** [comment]
Right, I remember messing around with Infinity Animations now, having IWD- and BG2-style shadows both in this huge BGT installation.

**Comment by lynxlynxlynx** [comment]
Yeah, just checked, they're fine in vanilla. I fixed it soon after your report: 2c92b7dcb80

Changing the animation type requires an edit to avatars.2da. Like the 14 changed to 4 in the above. Or in your case, I can't see mhsd (not mshd as expected) in any of the games, so if it's a new animation ID, it needs a new line, otherwise changing the bam names.

**Comment by caillean7** [comment]
... or changing the CRE files to use other animations with NearInfinity or DLTCEP. So we have workarounds for the time being.

**Comment by lynxlynxlynx** [comment]
Well, since we have a separate table, you can't expect random animation swaps to just work, as avatars.2da is the main source of truth. Mods changing the animation type of existing slots need to modify it too.

**Comment by caillean7** [comment]
>  they're fine in vanilla

You sure? At the risk of getting strangled through the internet line, I still have this issue on an unmodded game.
![shadows](https://user-images.githubusercontent.com/54738589/65833339-b4be7880-e2cf-11e9-8d34-3712142d8450.jpg)

**Comment by lynxlynxlynx** [comment]
I see:
![image](https://user-images.githubusercontent.com/121515/65836448-2bb83900-e2f1-11e9-8453-1e0e821f060c.png)

**Comment by caillean7** [comment]
Huh - sorry about that, no idea why those shadows are not drawn for me.

**Comment by lynxlynxlynx** [comment]
ctrl-m on them to see the animation info and effect queue (could be invisible?).

**Comment by caillean7** [comment]
OMG, pleasedontkillme - there was an avatars.2da file in the override folder (no idea how it got there), probably from the time before https://github.com/gemrb/gemrb/commit/2c92b7dcb803cceeb13a106b47a3c37b1d2a1eed. So it tried to use non-existent animations. Since I made a copy of this folder whenever I started a new BG2 installation, they all had shadow problems...
