### ISSUE TITLE
Unable to launch on a Raspberry Pi 4

### ISSUE THREAD

**Issue by luke243** [gemrb/gemrb#988]
#### Bug description
I've compiled GemRB v0.8.7 with SDL2 and the GLES backend on Rasbian however I'm unable to launch GemRB. I'm using a bg1 data directory that did work okay on another machine (power9/ppc64le with an AMD RX570 GPU).

I did try setting the backend to the desktop OpenGL one but it just ignored it and selected GLES again. Have working OpenGL 2.1 and OpenGL-ES 3.1 support.

GemRB version: v0.8.7

#### Steps to reproduce
Compile v0.8.7 on rasbian:
$ cmake -DSDL_BACKEND=SDL2 -DOPENGL_BACKEND=GLES ..
$ make
$ make install
$ cd /path/to/bg1
$ gemrb

#### Expected behavior
Expected to launch without errors.

#### GemRB log
[Core]: GemRB Core Initialization...
[Core]: Initializing Video Driver...
[Core]: Initializing Search Path...
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/portraits (Portraits)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/data/Data (Data)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/CD1/data (CD1/data)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/data/CD1/data (CD1/data)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/CD2/data (CD2/data)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/data/CD2/data (CD2/data)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/CD3/data (CD3/data)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/data/CD3/data (CD3/data)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/CD4/data (CD4/data)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/data/CD4/data (CD4/data)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/CD5/data (CD5/data)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/data/CD5/data (CD5/data)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/CD6/data (CD6/data)
[ResourceManager/WARNING]: Invalid path given: /home/luke/games/bg1/data/CD6/data (CD6/data)
[Core]: Initializing KEY Importer...
[KEYImporter]: Opening /home/luke/games/bg1/chitin.key...
[KEYImporter]: Checking file type...
[KEYImporter]: Reading Resources...
[KEYImporter]: BIF Files Count: 160 (Starting at 24 Bytes)
[KEYImporter]: RES Count: 16695 (Starting at 4810 Bytes)
[KEYImporter]: Resources Loaded...
[Core]: Initializing GUI Script Engine...
[SDL 2 GL Driver]: Creating display
[SDL 2 GL Driver]: Creating Main Surface: w=1920 h=1080 fmt=SDL_PIXELFORMAT_RGBA8888
[SDL 2 GL Driver/FATAL]: Can't build shader program: 0:1(1): error: syntax error, unexpected NEW_IDENTIFIER

[Core/FATAL]: Cannot initialize shaders.
[Main]: Aborting due to fatal error...

**Comment by lynxlynxlynx** [comment]
This has been fixed already — try building from git.

**Comment by luke243** [comment]
Thanks, apologies for raising something that's already been fixed.

**Comment by 2play** [comment]
@lynxlynxlynx 
Hi there

Apologies for writing to a closed by @luke243  issue but compiling rom git latest code fails at around 35% ...

Only code from releases 0.8.7 compiles ok with above but gemrb still cant launch a game neither as SDL nor on Pi4 Desktop with GLES driver

RetroPie compile scriptmodule compiles 0.8.6 code with SDL backend and runs OK..

I notice in cmake options if RPI found to apply SDL + GLES

Here is what I tried and my pastebin error. Much appreciated any comments

Built from Git with
`git clone https://github.com/gemrb/gemrb.git`
 
And build folder with
`cmake .. -DCMAKE_BUILD_TYPE=Release -DFREETYPE_INCLUDE_DIRS=/usr/include/freetype2/  -DUSE_SDLMIXER=OFF -DOPENGL_BACKEND=GLES -DSDL_BACKEND=SDL2`
 
qte
--
-- Options:
--   LAYOUT: fhs
--   NOCOLOR: disabled
--   STATIC_LINK: disabled
--   INSOURCEBUILD: disabled
--   DISABLE_WERROR: disabled
--   WIN32_USE_STDIO: disabled
--   SDL_BACKEND: SDL2
--   OPENGL_BACKEND: GLES
uqte

PASTEBIN
[](https://pastebin.com/kfWdutmJ)
